<?php

// autoload.php @generated by Composer

include_once G5_ERP_PATH."/extend/vender/arialunicid0.php";
// require_once __DIR__ . '/composer/autoload_real.php';

include_once G5_ERP_PATH."/extend/vender/composer/autoload_real.php";

return ComposerAutoloaderInit8798a0c46c044266d6bec35a0056b07e::getLoader();
